---
title: "GaliWatch Data Dashboard"
output: 
  flexdashboard::flex_dashboard:
    theme: readable
    orientation: rows
    css: static/extra.css
runtime: shiny
---


```{r global, include=FALSE, warning=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard

library(flexdashboard)
library(dplyr)
library(lubridate)
library(plotly)
library(ggplot2)
library(googlesheets4)
source('helpers.R')
gs4_deauth()


ep_id <- '18NDBVmR90-vh-sBlEiAqfRN6XSqHd2_LPkrkyf0i0ZM'
ws_id <- '1UKZGQyFB_Zqxr5qxvNoqTj26pm01lsclba1kYEzchbQ'

ep <- read_sheet(ep_id) %>%
  mutate(Date = dmy(Date),
         Time = hms::as_hms(Time)) 

ws <- read_sheet(ws_id) %>%
  mutate(Date = ymd(Date),
         Time = hms::as_hms(Time))
```



Day view {data-icon="fa-sun"}
===================================== 


Row {data-height=85}

-------------------------------------

### Date 

```{r}
date_range_min <- max(min(ep$Date), min(ws$Date))
date_range_max <- min(max(ep$Date), max(ws$Date))
 
dateInput("one_day", label = "Pick Day", value = date('2021-04-01'),
          min = date_range_min, max = date_range_max)

fc_switch(label='Units', inputId = 'tmp_unit')
```

### Low

```{r}
renderValueBox({
  
lo <- ep %>% 
  subset(Date == input$one_day) %>%
  summarise(min(temperature))
  
temp <- ifelse(input$tmp_unit,
               paste0(round(lo,2),"째C"), 
               paste0(round(c2f(lo),2), "째F"))


valueBox(temp, icon = "fa-thermometer-quarter", color = '#448878')
  
})
```

### High

```{r}
renderValueBox({
  
hi <- ep %>% 
  subset(Date == input$one_day) %>% 
  summarise(max(temperature)) 

temp <- ifelse(input$tmp_unit,
               paste0(round(hi,2),"째C"), 
               paste0(round(c2f(hi),2), "째F")) 

valueBox(temp, icon = "fa-thermometer-full", color = '#448878')

})
```

### Average Humidity

```{r}
renderGauge({

ep %>%
  subset(Date == input$one_day) %>%
  summarise(mean(humidity)) %>%
  round(2) %>%
  as.numeric() %>%
    
gauge(0, 100, gaugeSectors(colors = '#69b3a2'))
  
})
```


Row 
-------------------------------------

### Temperature

```{r}
renderPlotly({
  
ws %>%
  filter(Date == input$one_day) %>%
  mutate(y1=`Indoor Temperature F`) %>%
  plot_ly(x = ~Time, type = 'scatter', mode = 'lines+markers',
          y = ~y1, name = 'Indoor Temp') %>%
  add_trace(y = ~`Outdoor Temperature F`, name = 'Outdoor Temp') %>%
  add_trace(y = ~`Dew Point`, name = 'Dew Point') %>%
  add_trace(y = ~`Feels like`, name = 'Feels Like') %>%
  layout(yaxis = list(title = 'Temperature (F)'), hovermode = "x unified",
         colorway = tsc(4)) 
  
})
``` 

### Air Quality

```{r}
plot(1:20)
```

10-day view {data-icon="fa-calendar-alt"}
=====================================

Column {.sidebar}
-----------------------------------------------------------------------

Browse 10-day historical data. Weather data collected as part of [Operation Galiwatch](https://harrig12.github.io/galiwatch/)

```{r}
#dateInput("last_day", label = "Pick Day", value = max(weather$Date, na.rm = T), 
#          min = min(weather$Date, na.rm = T) + 10, max = max(weather$Date, na.rm = T))

dateInput("last_day", label = "Pick Day", value = date('2021-03-01'), 
          min = date("2021-02-26"), max = date('2021-03-11'))

n_days = 10
```

Row {data-height=400}
-------------------------------------
    
### Temperature

```{r}
renderPlotly({

ws %>%
  filter(Date <= input$last_day, Date >= (input$last_day-n_days)) %>%
  tail(n_days) %>%
  plot_ly(x = ~Date, type = 'scatter', mode = 'lines+markers', colors = "Set2",
          y = ~`Indoor Temperature F`, name = 'Indoor Temp') %>%
  add_trace(y = ~`Outdoor Temperature F`, name = 'Outdoor Temp') %>%
  add_trace(y = ~`Dew Point`, name = 'Dew Point') %>%
  add_trace(y = ~`Feels like`, name = 'Feels Like') %>%
  layout(yaxis = list(title = 'Temperature (F)'), hovermode = "x unified",
         colorway = tsc(4)) 
  
})
``` 

### Data sparsity

```{r}

renderText({ 
    sparce <- ws %>% filter(Date <= input$last_day, Date >= (input$last_day-n_days))
    paste("In selected timeframe, data was picked up for ",  sum((dim(sparce)[1] - colSums(is.na(sparce))) != 0)," out of 24 sensors.")
})

renderGauge({

mean_missing <- ws %>%
  filter(Date <= input$last_day, Date >= (input$last_day-n_days)) %>%
  is.na() %>% rowSums() %>% max()

gauge(mean_missing, 
      gaugeSectors(success = c(0, 0.3 * dim(ws)[2]), 
                   warning = c(0.3 * dim(ws)[2], 0.6 * dim(ws)[2]),
                   danger = c(0.6 * dim(ws)[2], dim(ws)[2])),
        min = 0, max = 100)
})
```

Row
-------------------------------------
   
### Humidity
    
```{r}
renderPlotly({

ws %>%
  filter(Date < input$last_day, Date > (input$last_day -n_days)) %>%
  tail(n_days) %>%
  plot_ly(x = ~Date, type = 'scatter', mode = 'lines+markers', colors = "Set2",
          y = ~`Indoor Humidity %`, name = 'Indoor Humidity') %>%
  add_trace(y = ~`Outdoor Humidity %`, name = 'Outdoor Humidity') %>%
  layout(yaxis = list(title = 'Humidity (%)'), hovermode = "x unified",
         colorway = tsc(4)) 
  
})
```

### Wind rose

```{r}
renderPlot({
  
ws %>%
  filter(Date < input$last_day, Date > (input$last_day -n_days)) %>%
  windRose(ws = "Wind Speed(mph)" , wd = "wind direction(Degree)")


})

ws %>%
  subset(Date == '2021-02-15', y_bins=10) %>%
  windrose()


```



